#!/usr/bin/env tsx
/**
 * patch-country-data.ts
 * Cập nhật dữ liệu "Needs verification" / "Data unavailable" trong DB.
 * Nguồn: Wikipedia, CIA World Factbook, Wikidata — đến ngày 5/6/2026.
 *
 * Chạy: npx tsx scripts/patch-country-data.ts
 */

import { DatabaseSync } from "node:sqlite";
import fs from "node:fs";
import path from "node:path";

const DB_PATH = path.resolve(process.cwd(), "./data/world-ideology-atlas.db");

// ─── Dữ liệu patch ─────────────────────────────────────────────────────────
// Mỗi entry key là iso3. Chỉ các field cần cập nhật được liệt kê.
// Các field không có trong patch sẽ giữ nguyên giá trị từ DB.

export const PATCHES: Record<string, Record<string, unknown>> = {
  // ── VIỆT NAM ──────────────────────────────────────────────
  VNM: {
    headOfStateTitle: "Tổng Bí thư kiêm Chủ tịch nước",
    headOfState: "Tô Lâm",
    headOfGovernmentTitle: "Thủ tướng Chính phủ",
    headOfGovernment: "Lê Minh Hưng",
    rulingParty: "Đảng Cộng sản Việt Nam",
    judiciary: "Tòa án nhân dân tối cao",
    constitution: "Hiến pháp Việt Nam 2013",
    constitutionYear: 2013,
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── HOA KỲ ────────────────────────────────────────────────
  USA: {
    headOfStateTitle: "President",
    headOfState: "Donald Trump",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Donald Trump",
    rulingParty: "Republican Party",
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── TRUNG QUỐC ───────────────────────────────────────────
  CHN: {
    headOfStateTitle: "President",
    headOfState: "Xi Jinping",
    headOfGovernmentTitle: "Premier",
    headOfGovernment: "Li Qiang",
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ANH ──────────────────────────────────────────────────
  GBR: {
    headOfStateTitle: "Monarch",
    headOfState: "King Charles III",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Sir Keir Starmer",
    rulingParty: "Labour Party",
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── THỤY ĐIỂN ────────────────────────────────────────────
  SWE: {
    headOfStateTitle: "Monarch",
    headOfState: "King Carl XVI Gustaf",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Ulf Kristersson",
    rulingParty: "Moderate Party (coalition)",
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── CUBA ─────────────────────────────────────────────────
  CUB: {
    headOfStateTitle: "President",
    headOfState: "Miguel Díaz-Canel",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Manuel Marrero Cruz",
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── PHÁP ─────────────────────────────────────────────────
  FRA: {
    stateForm: "Unitary semi-presidential republic",
    governmentSystem: "Semi-presidential constitutional republic",
    constitutionalIdentity: "Secular unitary republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberalism", "Republicanism", "Laïcité"],
    politicalRegime: "Semi-presidential multi-party democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Executive power shared between elected President and Prime Minister responsible to the National Assembly.",
    headOfStateTitle: "President",
    headOfState: "Emmanuel Macron",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "François Bayrou",
    rulingParty: "Renaissance (coalition)",
    partySystem: "Multi-party system",
    legislature: "Parliament of France",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Council; Court of Cassation",
    constitution: "Constitution of the Fifth Republic",
    constitutionYear: 1958,
    economicModel: "Mixed market economy with welfare-state institutions",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    summary: "France is a unitary semi-presidential republic with a mixed political system balancing presidential and parliamentary elements, and a diversified market economy.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/france/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ĐỨC ──────────────────────────────────────────────────
  DEU: {
    stateForm: "Federal parliamentary republic",
    governmentSystem: "Federal parliamentary constitutional republic",
    constitutionalIdentity: "Federal democratic and social republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism", "Social market economy"],
    politicalRegime: "Parliamentary multi-party democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Federal government responsible to the Bundestag; President is largely ceremonial.",
    headOfStateTitle: "Federal President",
    headOfState: "Frank-Walter Steinmeier",
    headOfGovernmentTitle: "Federal Chancellor",
    headOfGovernment: "Friedrich Merz",
    rulingParty: "CDU/CSU (coalition with SPD)",
    partySystem: "Multi-party system",
    legislature: "Bundestag",
    legislatureStructure: "Bicameral",
    judiciary: "Federal Constitutional Court",
    constitution: "Basic Law (Grundgesetz)",
    constitutionYear: 1949,
    economicModel: "Social market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    summary: "Germany is a federal parliamentary republic with a social market economy, governed by coalition governments under a strong constitutional framework.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/germany/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── NHẬT BẢN ─────────────────────────────────────────────
  JPN: {
    stateForm: "Unitary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy with parliamentary government",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Constitutional monarchy", "Pacifism"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Executive power is exercised by the Cabinet, which is collectively responsible to the National Diet.",
    headOfStateTitle: "Emperor",
    headOfState: "Emperor Naruhito",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Sanae Takaichi",
    rulingParty: "Liberal Democratic Party (LDP)",
    partySystem: "Multi-party system with dominant party",
    legislature: "National Diet",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of Japan",
    constitution: "Constitution of Japan",
    constitutionYear: 1947,
    economicModel: "Mixed market economy with strong industrial base",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    summary: "Japan is a parliamentary constitutional monarchy with Emperor Naruhito as head of state and a democratic multi-party government led by the LDP.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/japan/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── HÀN QUỐC ─────────────────────────────────────────────
  KOR: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Directly elected President serves as both head of state and head of government.",
    headOfStateTitle: "President",
    headOfState: "Lee Jae-myung",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Lee Jae-myung",
    rulingParty: "Democratic Party of Korea",
    partySystem: "Multi-party system",
    legislature: "National Assembly",
    legislatureStructure: "Unicameral",
    judiciary: "Constitutional Court; Supreme Court",
    constitution: "Constitution of the Republic of Korea",
    constitutionYear: 1948,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    summary: "South Korea is a unitary presidential republic with a vibrant multi-party democracy and a highly developed market economy.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/south-korea/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ẤN ĐỘ ────────────────────────────────────────────────
  IND: {
    stateForm: "Federal parliamentary republic",
    governmentSystem: "Federal parliamentary constitutional republic",
    constitutionalIdentity: "Sovereign, socialist, secular, democratic republic",
    officialIdeology: "No single official ideology; Constitutional values of secularism and democracy",
    ideologyFamily: ["Liberal democracy", "Federalism", "Secularism"],
    politicalRegime: "Parliamentary multi-party democracy",
    regimeCategory: "Electoral democracy",
    powerStructure: "Executive power is exercised by Prime Minister and Cabinet, accountable to Parliament.",
    headOfStateTitle: "President",
    headOfState: "Droupadi Murmu",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Narendra Modi",
    rulingParty: "Bharatiya Janata Party (BJP) / NDA coalition",
    partySystem: "Multi-party federal system",
    legislature: "Parliament of India",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of India",
    constitution: "Constitution of India",
    constitutionYear: 1950,
    economicModel: "Mixed economy with market liberalization",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    summary: "India is the world's largest democracy, a federal parliamentary republic with a multi-party system and a mixed economy undergoing market reforms.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/india/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── AUSTRALIA ────────────────────────────────────────────
  AUS: {
    stateForm: "Federal parliamentary constitutional monarchy",
    governmentSystem: "Federal parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy with parliamentary government",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism", "Constitutional monarchy"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Executive power is exercised by Prime Minister and Cabinet, responsible to Parliament.",
    headOfStateTitle: "Monarch",
    headOfState: "King Charles III",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Anthony Albanese",
    rulingParty: "Australian Labor Party",
    partySystem: "Two-party dominant system",
    legislature: "Parliament of Australia",
    legislatureStructure: "Bicameral",
    judiciary: "High Court of Australia",
    constitution: "Constitution of Australia",
    constitutionYear: 1901,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: true,
    isUnitary: false,
    summary: "Australia is a federal parliamentary constitutional monarchy with King Charles III as head of state and a Westminster-style democratic government.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/australia/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── BRAZIL ───────────────────────────────────────────────
  BRA: {
    stateForm: "Federal presidential republic",
    governmentSystem: "Federal presidential constitutional republic",
    constitutionalIdentity: "Federative republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism", "Social democracy"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral democracy",
    powerStructure: "Directly elected President serves as both head of state and government in a federal system.",
    headOfStateTitle: "President",
    headOfState: "Luiz Inácio Lula da Silva",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Luiz Inácio Lula da Silva",
    rulingParty: "Workers' Party (PT) / coalition",
    partySystem: "Multi-party system",
    legislature: "National Congress of Brazil",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Federal Court",
    constitution: "Constitution of Brazil",
    constitutionYear: 1988,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    summary: "Brazil is a federal presidential republic with a diverse multi-party system and a large emerging market economy.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/brazil/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── CANADA ───────────────────────────────────────────────
  CAN: {
    stateForm: "Federal parliamentary constitutional monarchy",
    governmentSystem: "Federal parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy with parliamentary government",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism", "Constitutional monarchy"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Executive power is exercised by Prime Minister and Cabinet, responsible to Parliament.",
    headOfStateTitle: "Monarch",
    headOfState: "King Charles III",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Mark Carney",
    rulingParty: "Liberal Party of Canada",
    partySystem: "Multi-party system",
    legislature: "Parliament of Canada",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of Canada",
    constitution: "Constitution Act",
    constitutionYear: 1982,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: true,
    isUnitary: false,
    summary: "Canada is a federal parliamentary constitutional monarchy with a Westminster-style government and a mixed market economy.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/canada/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── NGA ──────────────────────────────────────────────────
  NGA: {
    stateForm: "Federal presidential republic",
    governmentSystem: "Federal presidential constitutional republic",
    constitutionalIdentity: "Federal republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Directly elected President serves as head of state and government in a federal system.",
    headOfStateTitle: "President",
    headOfState: "Bola Ahmed Tinubu",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Bola Ahmed Tinubu",
    rulingParty: "All Progressives Congress (APC)",
    partySystem: "Multi-party system",
    legislature: "National Assembly",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of Nigeria",
    constitution: "Constitution of Nigeria",
    constitutionYear: 1999,
    economicModel: "Mixed market economy with oil-dependent exports",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    summary: "Nigeria is Africa's most populous country and a federal presidential republic with a multi-party democracy and oil-dependent economy.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/nigeria/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── NAM PHI ──────────────────────────────────────────────
  ZAF: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Constitutional democracy",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism", "Non-racialism"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral democracy",
    powerStructure: "Directly elected President serves as both head of state and government.",
    headOfStateTitle: "President",
    headOfState: "Cyril Ramaphosa",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Cyril Ramaphosa",
    rulingParty: "African National Congress (ANC) / GNU coalition",
    partySystem: "Multi-party system",
    legislature: "Parliament of South Africa",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court; Supreme Court of Appeal",
    constitution: "Constitution of South Africa",
    constitutionYear: 1996,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    summary: "South Africa is a unitary presidential republic with a strong constitutional framework and a government of national unity led by the ANC.",
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/south-africa/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── KENYA ────────────────────────────────────────────────
  KEN: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Constitutional republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Directly elected President serves as head of state and government.",
    headOfStateTitle: "President",
    headOfState: "William Ruto",
    headOfGovernmentTitle: "President",
    headOfGovernment: "William Ruto",
    rulingParty: "Kenya Kwanza coalition",
    partySystem: "Multi-party system",
    legislature: "Parliament of Kenya",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of Kenya",
    constitution: "Constitution of Kenya",
    constitutionYear: 2010,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/kenya/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── AI CẬP ───────────────────────────────────────────────
  EGY: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential republic",
    constitutionalIdentity: "Arab Republic",
    officialIdeology: "Arab nationalism; Islam as state religion",
    ideologyFamily: ["Arab nationalism", "Statism"],
    politicalRegime: "Presidential republic with limited political competition",
    regimeCategory: "Closed autocracy",
    powerStructure: "President holds dominant executive power; Parliament has limited independence.",
    headOfStateTitle: "President",
    headOfState: "Abdel Fattah el-Sisi",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Mostafa Madbouly",
    rulingParty: "Nation's Future Party",
    partySystem: "Dominant-party system",
    legislature: "Parliament of Egypt",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Constitutional Court",
    constitution: "Constitution of Egypt",
    constitutionYear: 2014,
    economicModel: "Mixed economy with state-led sectors",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/egypt/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ETHIOPIA ─────────────────────────────────────────────
  ETH: {
    stateForm: "Federal parliamentary republic",
    governmentSystem: "Federal parliamentary republic",
    constitutionalIdentity: "Federal democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism"],
    politicalRegime: "Parliamentary republic with dominant ruling party",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Prime Minister holds executive power; President is largely ceremonial.",
    headOfStateTitle: "President",
    headOfState: "Taye Atske Selassie",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Abiy Ahmed",
    rulingParty: "Prosperity Party",
    partySystem: "Multi-party system with dominant party",
    legislature: "Parliament of Ethiopia",
    legislatureStructure: "Bicameral",
    judiciary: "Federal Supreme Court",
    constitution: "Constitution of Ethiopia",
    constitutionYear: 1995,
    economicModel: "Mixed economy with state-led development",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/ethiopia/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── GHANA ────────────────────────────────────────────────
  GHA: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Directly elected President serves as head of state and government.",
    headOfStateTitle: "President",
    headOfState: "John Dramani Mahama",
    headOfGovernmentTitle: "President",
    headOfGovernment: "John Dramani Mahama",
    rulingParty: "National Democratic Congress (NDC)",
    partySystem: "Two-party dominant system",
    legislature: "Parliament of Ghana",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Ghana",
    constitution: "Constitution of Ghana",
    constitutionYear: 1992,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/ghana/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── Ý ────────────────────────────────────────────────────
  ITA: {
    stateForm: "Unitary parliamentary republic",
    governmentSystem: "Parliamentary constitutional republic",
    constitutionalIdentity: "Democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Parliamentary multi-party democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Prime Minister leads the Cabinet, which is responsible to Parliament; President is largely ceremonial.",
    headOfStateTitle: "President",
    headOfState: "Sergio Mattarella",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Giorgia Meloni",
    rulingParty: "Brothers of Italy (FdI) / coalition",
    partySystem: "Multi-party system",
    legislature: "Parliament of Italy",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court of Italy",
    constitution: "Constitution of Italy",
    constitutionYear: 1948,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/italy/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── TÂY BAN NHA ──────────────────────────────────────────
  ESP: {
    stateForm: "Unitary parliamentary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Social and democratic state governed by the rule of law",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Constitutional monarchy", "Social democracy"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Prime Minister and Cabinet responsible to the Congress of Deputies; King is head of state.",
    headOfStateTitle: "Monarch",
    headOfState: "King Felipe VI",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Pedro Sánchez",
    rulingParty: "Spanish Socialist Workers' Party (PSOE) / coalition",
    partySystem: "Multi-party system",
    legislature: "Cortes Generales",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court of Spain",
    constitution: "Constitution of Spain",
    constitutionYear: 1978,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/spain/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── BA LAN ────────────────────────────────────────────────
  POL: {
    stateForm: "Unitary semi-presidential republic",
    governmentSystem: "Parliamentary republic with presidential elements",
    constitutionalIdentity: "Democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Parliamentary multi-party democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Prime Minister leads government; President has significant constitutional powers.",
    headOfStateTitle: "President",
    headOfState: "Andrzej Duda",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Donald Tusk",
    rulingParty: "Civic Coalition (KO) / coalition",
    partySystem: "Multi-party system",
    legislature: "National Assembly (Parliament)",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Tribunal",
    constitution: "Constitution of Poland",
    constitutionYear: 1997,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/poland/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── HÀ LAN ────────────────────────────────────────────────
  NLD: {
    stateForm: "Unitary parliamentary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Constitutional monarchy"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Prime Minister and Cabinet responsible to Parliament; King is largely ceremonial.",
    headOfStateTitle: "Monarch",
    headOfState: "King Willem-Alexander",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Rob Jetten",
    rulingParty: "VVD-led coalition",
    partySystem: "Multi-party system",
    legislature: "States-General",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of the Netherlands",
    constitution: "Constitution of the Netherlands",
    constitutionYear: 1815,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/netherlands/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── NA UY ─────────────────────────────────────────────────
  NOR: {
    stateForm: "Unitary parliamentary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Social democracy", "Constitutional monarchy"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Prime Minister and Cabinet responsible to Storting; King is largely ceremonial.",
    headOfStateTitle: "Monarch",
    headOfState: "King Harald V",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Jonas Gahr Støre",
    rulingParty: "Labour Party / coalition",
    partySystem: "Multi-party system",
    legislature: "Storting",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Norway",
    constitution: "Constitution of Norway",
    constitutionYear: 1814,
    economicModel: "Mixed market economy with large sovereign wealth fund",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/norway/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ĐAN MẠCH ─────────────────────────────────────────────
  DNK: {
    stateForm: "Unitary parliamentary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Social democracy", "Constitutional monarchy"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Prime Minister and Cabinet responsible to Folketing; Monarch is largely ceremonial.",
    headOfStateTitle: "Monarch",
    headOfState: "King Frederik X",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Mette Frederiksen",
    rulingParty: "Social Democrats / coalition",
    partySystem: "Multi-party system",
    legislature: "Folketing",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Denmark",
    constitution: "Constitution of Denmark",
    constitutionYear: 1953,
    economicModel: "Mixed market economy with welfare-state institutions",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/denmark/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── PHẦN LAN ─────────────────────────────────────────────
  FIN: {
    stateForm: "Unitary semi-presidential republic",
    governmentSystem: "Parliamentary republic with semi-presidential features",
    constitutionalIdentity: "Republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Prime Minister leads government; President has foreign policy roles.",
    headOfStateTitle: "President",
    headOfState: "Alexander Stubb",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Petteri Orpo",
    rulingParty: "National Coalition Party / coalition",
    partySystem: "Multi-party system",
    legislature: "Parliament of Finland",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Finland",
    constitution: "Constitution of Finland",
    constitutionYear: 2000,
    economicModel: "Mixed market economy with welfare-state institutions",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/finland/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── THỤY SĨ ──────────────────────────────────────────────
  CHE: {
    stateForm: "Federal directorial republic",
    governmentSystem: "Federal directorial republic",
    constitutionalIdentity: "Federal state",
    officialIdeology: "No single official ideology; direct democracy",
    ideologyFamily: ["Liberal democracy", "Federalism", "Direct democracy"],
    politicalRegime: "Parliamentary democracy with direct democracy elements",
    regimeCategory: "Liberal democracy",
    powerStructure: "Seven-member Federal Council acts collectively as head of state and government; presidency rotates annually.",
    headOfStateTitle: "President of the Swiss Confederation",
    headOfState: "Guy Parmelin",
    headOfGovernmentTitle: "President of the Swiss Confederation",
    headOfGovernment: "Guy Parmelin",
    rulingParty: "Federal Council (multi-party executive)",
    partySystem: "Multi-party system with consensus government",
    legislature: "Federal Assembly",
    legislatureStructure: "Bicameral",
    judiciary: "Federal Supreme Court",
    constitution: "Federal Constitution of Switzerland",
    constitutionYear: 1999,
    economicModel: "Mixed market economy with strong financial sector",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/switzerland/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ÁO ───────────────────────────────────────────────────
  AUT: {
    stateForm: "Federal parliamentary republic",
    governmentSystem: "Federal parliamentary republic",
    constitutionalIdentity: "Democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Federal Chancellor leads government; President has limited executive power.",
    headOfStateTitle: "Federal President",
    headOfState: "Alexander Van der Bellen",
    headOfGovernmentTitle: "Federal Chancellor",
    headOfGovernment: "Christian Stocker",
    rulingParty: "Austrian People's Party (ÖVP) / coalition",
    partySystem: "Multi-party system",
    legislature: "Parliament of Austria",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court of Austria",
    constitution: "Federal Constitutional Law",
    constitutionYear: 1920,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/austria/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── NGA (RUSSIA) ──────────────────────────────────────────
  RUS: {
    stateForm: "Federal semi-presidential republic",
    governmentSystem: "Federal semi-presidential constitutional republic",
    constitutionalIdentity: "Federal state governed by rule of law",
    officialIdeology: "Russian statism; conservative nationalism",
    ideologyFamily: ["Statism", "Conservative nationalism"],
    politicalRegime: "Presidential system with limited political competition",
    regimeCategory: "Closed autocracy",
    powerStructure: "President holds dominant executive power; Prime Minister heads the government.",
    headOfStateTitle: "President",
    headOfState: "Vladimir Putin",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Mikhail Mishustin",
    rulingParty: "United Russia",
    partySystem: "Dominant-party system",
    legislature: "Federal Assembly",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court of Russia",
    constitution: "Constitution of Russia",
    constitutionYear: 1993,
    economicModel: "Mixed market economy with state-led strategic sectors",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/russia/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── SINGAPORE ────────────────────────────────────────────
  SGP: {
    stateForm: "Unitary parliamentary republic",
    governmentSystem: "Parliamentary republic",
    constitutionalIdentity: "Constitutional republic",
    officialIdeology: "Pragmatism; meritocracy; multiracialism",
    ideologyFamily: ["Liberal democracy (guided)", "Statism", "Pragmatism"],
    politicalRegime: "Parliamentary republic with dominant ruling party",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Prime Minister leads the Cabinet; President serves as ceremonial head of state with limited custodial powers.",
    headOfStateTitle: "President",
    headOfState: "Tharman Shanmugaratnam",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Lawrence Wong",
    rulingParty: "People's Action Party (PAP)",
    partySystem: "Dominant-party system",
    legislature: "Parliament of Singapore",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Singapore",
    constitution: "Constitution of Singapore",
    constitutionYear: 1965,
    economicModel: "Free-market economy with state-led strategic sectors",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/singapore/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── INDONESIA ────────────────────────────────────────────
  IDN: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Unitary republic based on Pancasila",
    officialIdeology: "Pancasila",
    ideologyFamily: ["Pancasila ideology", "Nationalism", "Liberal democracy"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral democracy",
    powerStructure: "Directly elected President serves as head of state and government.",
    headOfStateTitle: "President",
    headOfState: "Prabowo Subianto",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Prabowo Subianto",
    rulingParty: "Gerindra / coalition",
    partySystem: "Multi-party system",
    legislature: "People's Consultative Assembly (MPR)",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court of Indonesia",
    constitution: "Constitution of Indonesia",
    constitutionYear: 1945,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/indonesia/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── MALAYSIA ─────────────────────────────────────────────
  MYS: {
    stateForm: "Federal parliamentary constitutional monarchy",
    governmentSystem: "Federal parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy",
    officialIdeology: "Rukun Negara (national ideology)",
    ideologyFamily: ["Liberal democracy", "Federalism", "Constitutional monarchy"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Prime Minister leads Cabinet; Yang di-Pertuan Agong is constitutional monarch.",
    headOfStateTitle: "Yang di-Pertuan Agong",
    headOfState: "King Sultan Ibrahim",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Anwar Ibrahim",
    rulingParty: "Pakatan Harapan / unity coalition",
    partySystem: "Multi-party coalition system",
    legislature: "Parliament of Malaysia",
    legislatureStructure: "Bicameral",
    judiciary: "Federal Court of Malaysia",
    constitution: "Constitution of Malaysia",
    constitutionYear: 1957,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/malaysia/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── THÁI LAN ─────────────────────────────────────────────
  THA: {
    stateForm: "Unitary parliamentary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy",
    officialIdeology: "Nation, Religion, Monarchy",
    ideologyFamily: ["Conservative nationalism", "Constitutional monarchy"],
    politicalRegime: "Parliamentary democracy (post-junta transition)",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Prime Minister leads Cabinet; King is head of state.",
    headOfStateTitle: "Monarch",
    headOfState: "King Vajiralongkorn (Rama X)",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Anutin Charnvirakul",
    rulingParty: "Bhumjaithai Party / coalition",
    partySystem: "Multi-party system",
    legislature: "National Assembly of Thailand",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court of Thailand",
    constitution: "Constitution of Thailand",
    constitutionYear: 2017,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/thailand/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── PHILIPPINES ──────────────────────────────────────────
  PHL: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Democratic and republican state",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral democracy",
    powerStructure: "Directly elected President serves as head of state and government.",
    headOfStateTitle: "President",
    headOfState: "Ferdinand R. Marcos Jr.",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Ferdinand R. Marcos Jr.",
    rulingParty: "PFP / broad coalition",
    partySystem: "Multi-party system",
    legislature: "Congress of the Philippines",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of the Philippines",
    constitution: "Constitution of the Philippines",
    constitutionYear: 1987,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/philippines/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── LÀO ──────────────────────────────────────────────────
  LAO: {
    stateForm: "Unitary socialist republic",
    governmentSystem: "One-party socialist republic",
    constitutionalIdentity: "People's Democratic Republic",
    officialIdeology: "Marxism-Leninism",
    ideologyFamily: ["Socialism", "Marxism-Leninism", "Communism"],
    politicalRegime: "One-party state",
    regimeCategory: "Closed autocracy",
    powerStructure: "Lao People's Revolutionary Party leads the state and society.",
    headOfStateTitle: "President",
    headOfState: "Thongloun Sisoulith",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Sonexay Siphandone",
    rulingParty: "Lao People's Revolutionary Party (LPRP)",
    partySystem: "One-party system",
    legislature: "National Assembly",
    legislatureStructure: "Unicameral",
    judiciary: "People's Supreme Court",
    constitution: "Constitution of Laos",
    constitutionYear: 1991,
    economicModel: "Transitioning socialist economy with market elements",
    hasCommunistRulingParty: true,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/laos/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── CAMPUCHIA ─────────────────────────────────────────────
  KHM: {
    stateForm: "Unitary parliamentary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy",
    officialIdeology: "Khmer nationalism; Buddhism",
    ideologyFamily: ["Conservative nationalism", "Constitutional monarchy"],
    politicalRegime: "Parliamentary monarchy with dominant ruling party",
    regimeCategory: "Closed autocracy",
    powerStructure: "Prime Minister leads government; King is ceremonial head of state.",
    headOfStateTitle: "Monarch",
    headOfState: "King Norodom Sihamoni",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Hun Manet",
    rulingParty: "Cambodian People's Party (CPP)",
    partySystem: "Dominant-party system",
    legislature: "National Assembly of Cambodia",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Council of Cambodia",
    constitution: "Constitution of Cambodia",
    constitutionYear: 1993,
    economicModel: "Market economy with development assistance",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/cambodia/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── MYANMAR ──────────────────────────────────────────────
  MMR: {
    stateForm: "Unitary military-governed state",
    governmentSystem: "Military government (State Administration Council)",
    constitutionalIdentity: "Republic (suspended under military rule since 2021)",
    officialIdeology: "Burmese nationalism; Buddhist nationalism",
    ideologyFamily: ["Military nationalism", "Buddhist nationalism"],
    politicalRegime: "Military junta",
    regimeCategory: "Closed autocracy",
    powerStructure: "Military junta (State Administration Council) controls all state functions since the February 2021 coup.",
    headOfStateTitle: "President",
    headOfState: "Min Aung Hlaing",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Min Aung Hlaing",
    rulingParty: "Union Solidarity and Development Party (USDP) / military",
    partySystem: "Military-controlled",
    legislature: "Pyidaungsu Hluttaw (suspended)",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court (under military control)",
    constitution: "Constitution of Myanmar 2008 (suspended)",
    constitutionYear: 2008,
    economicModel: "Mixed economy under military management",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: true,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/burma/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── TRIỀU TIÊN ───────────────────────────────────────────
  PRK: {
    stateForm: "Unitary socialist republic",
    governmentSystem: "Juche-based one-party socialist republic",
    constitutionalIdentity: "Socialist state",
    officialIdeology: "Juche; Kimilsungism-Kimjongilism; Songun",
    ideologyFamily: ["Juche", "Socialism", "Marxism-Leninism (adapted)"],
    politicalRegime: "Totalitarian one-party state",
    regimeCategory: "Closed autocracy",
    powerStructure: "Kim Jong Un holds supreme leadership as General Secretary of the Workers' Party and Chairman of the State Affairs Commission.",
    headOfStateTitle: "General Secretary / Supreme Leader",
    headOfState: "Kim Jong Un",
    headOfGovernmentTitle: "Premier",
    headOfGovernment: "Kim Tok Hun",
    rulingParty: "Workers' Party of Korea (WPK)",
    partySystem: "One-party system",
    legislature: "Supreme People's Assembly",
    legislatureStructure: "Unicameral",
    judiciary: "Central Court",
    constitution: "Constitution of North Korea",
    constitutionYear: 1972,
    economicModel: "Centrally planned socialist economy",
    hasCommunistRulingParty: true,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/korea-north/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── SAUDI ARABIA ─────────────────────────────────────────
  SAU: {
    stateForm: "Unitary absolute monarchy",
    governmentSystem: "Absolute monarchy under Islamic law",
    constitutionalIdentity: "Islamic state; Quran and Sunnah as constitution",
    officialIdeology: "Wahhabism; Islamic governance",
    ideologyFamily: ["Islamic governance", "Absolute monarchy"],
    politicalRegime: "Absolute monarchy",
    regimeCategory: "Closed autocracy",
    powerStructure: "King serves as head of state and government; political parties are banned.",
    headOfStateTitle: "King",
    headOfState: "King Salman bin Abdulaziz Al Saud",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Crown Prince Mohammed bin Salman",
    rulingParty: "House of Saud (no political parties)",
    partySystem: "No political parties",
    legislature: "Consultative Assembly (Majlis al-Shura)",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court (Islamic law)",
    constitution: "Basic Law of Governance",
    constitutionYear: 1992,
    economicModel: "Oil-based state economy with Vision 2030 diversification",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/saudi-arabia/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── THỔ NHĨ KỲ ───────────────────────────────────────────
  TUR: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Democratic, secular, social state governed by rule of law",
    officialIdeology: "Kemalism; Turkish nationalism",
    ideologyFamily: ["Kemalism", "Turkish nationalism", "Secularism"],
    politicalRegime: "Presidential republic with dominant ruling party",
    regimeCategory: "Electoral autocracy",
    powerStructure: "President serves as both head of state and government with broad executive powers.",
    headOfStateTitle: "President",
    headOfState: "Recep Tayyip Erdoğan",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Recep Tayyip Erdoğan",
    rulingParty: "Justice and Development Party (AKP)",
    partySystem: "Multi-party system with dominant party",
    legislature: "Grand National Assembly",
    legislatureStructure: "Unicameral",
    judiciary: "Constitutional Court of Turkey",
    constitution: "Constitution of Turkey",
    constitutionYear: 1982,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/turkey/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── IRAN ─────────────────────────────────────────────────
  IRN: {
    stateForm: "Unitary Islamic republic",
    governmentSystem: "Islamic Republic with theocratic elements",
    constitutionalIdentity: "Islamic Republic",
    officialIdeology: "Twelver Shi'a Islam; Velayat-e Faqih",
    ideologyFamily: ["Political Islam", "Theocracy", "Khomeinism"],
    politicalRegime: "Islamic republic with limited political competition",
    regimeCategory: "Closed autocracy",
    powerStructure: "Supreme Leader (Rahbar) holds supreme authority over all state institutions.",
    headOfStateTitle: "Supreme Leader",
    headOfState: "Mojtaba Khamenei",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Masoud Pezeshkian",
    rulingParty: "Conservative / Principlist coalition",
    partySystem: "Restricted multi-party system",
    legislature: "Islamic Consultative Assembly",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Iran",
    constitution: "Constitution of Iran",
    constitutionYear: 1979,
    economicModel: "State-led economy under sanctions",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/iran/", field: "governmentSystem" },
      { name: "Our World in Data / Regimes of the World", url: "https://ourworldindata.org/grapher/political-regime", field: "regimeCategory" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ISRAEL ───────────────────────────────────────────────
  ISR: {
    stateForm: "Unitary parliamentary republic",
    governmentSystem: "Parliamentary republic",
    constitutionalIdentity: "Jewish and democratic state",
    officialIdeology: "Zionism; Jewish democracy",
    ideologyFamily: ["Zionism", "Liberal democracy"],
    politicalRegime: "Parliamentary multi-party democracy",
    regimeCategory: "Electoral democracy",
    powerStructure: "Prime Minister leads coalition government; President is largely ceremonial.",
    headOfStateTitle: "President",
    headOfState: "Isaac Herzog",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Benjamin Netanyahu",
    rulingParty: "Likud / coalition",
    partySystem: "Multi-party system",
    legislature: "Knesset",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Israel",
    constitution: "Basic Laws of Israel (no formal constitution)",
    economicModel: "Mixed market economy with strong tech sector",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/israel/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── JORDAN ───────────────────────────────────────────────
  JOR: {
    stateForm: "Unitary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy",
    officialIdeology: "Hashemite nationalism; Islam",
    ideologyFamily: ["Constitutional monarchy", "Arab nationalism"],
    politicalRegime: "Constitutional monarchy with parliamentary elements",
    regimeCategory: "Electoral autocracy",
    powerStructure: "King holds significant executive power; Prime Minister leads government.",
    headOfStateTitle: "King",
    headOfState: "King Abdullah II",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Jafar Hassan",
    rulingParty: "Independent / tribal-based government",
    partySystem: "Multi-party system with limited influence",
    legislature: "National Assembly of Jordan",
    legislatureStructure: "Bicameral",
    judiciary: "Court of Cassation",
    constitution: "Constitution of Jordan",
    constitutionYear: 1952,
    economicModel: "Mixed market economy with foreign aid dependency",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/jordan/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── UAE ──────────────────────────────────────────────────
  ARE: {
    stateForm: "Federal constitutional monarchy",
    governmentSystem: "Federal presidential absolute monarchy",
    constitutionalIdentity: "Federal state of constitutional monarchies",
    officialIdeology: "Arab nationalism; Islam; modernization",
    ideologyFamily: ["Islamic governance", "Arab nationalism", "Absolute monarchy"],
    politicalRegime: "Federal monarchy with consultative institutions",
    regimeCategory: "Closed autocracy",
    powerStructure: "President is head of state; Prime Minister leads government; no elected parliament.",
    headOfStateTitle: "President",
    headOfState: "Sheikh Mohamed bin Zayed Al Nahyan",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Sheikh Mohammed bin Rashid Al Maktoum",
    rulingParty: "No political parties",
    partySystem: "No political parties",
    legislature: "Federal National Council (appointed/partially elected)",
    legislatureStructure: "Unicameral",
    judiciary: "Federal Supreme Court",
    constitution: "Constitution of the United Arab Emirates",
    constitutionYear: 1971,
    economicModel: "Diversified market economy with oil wealth",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/united-arab-emirates/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── QATAR ────────────────────────────────────────────────
  QAT: {
    stateForm: "Unitary constitutional monarchy",
    governmentSystem: "Constitutional emirate (absolute monarchy in practice)",
    constitutionalIdentity: "Arab Islamic state",
    officialIdeology: "Islamic governance; Qatari nationalism",
    ideologyFamily: ["Islamic governance", "Absolute monarchy"],
    politicalRegime: "Absolute monarchy",
    regimeCategory: "Closed autocracy",
    powerStructure: "Emir holds supreme executive and legislative authority.",
    headOfStateTitle: "Emir",
    headOfState: "Sheikh Tamim bin Hamad Al Thani",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Sheikh Mohammed bin Abdulrahman Al Thani",
    rulingParty: "House of Thani (no political parties)",
    partySystem: "No political parties",
    legislature: "Consultative Assembly (Majlis al-Shura)",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Qatar",
    constitution: "Constitution of Qatar",
    constitutionYear: 2003,
    economicModel: "Oil and gas-based state economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/qatar/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── KUWAIT ───────────────────────────────────────────────
  KWT: {
    stateForm: "Unitary constitutional monarchy",
    governmentSystem: "Constitutional emirate",
    constitutionalIdentity: "Arab Islamic state",
    officialIdeology: "Islamic governance; Arab nationalism",
    ideologyFamily: ["Constitutional monarchy", "Islamic governance"],
    politicalRegime: "Constitutional monarchy with elected parliament",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Emir serves as head of state; Crown Prince / Prime Minister leads government; elected National Assembly.",
    headOfStateTitle: "Emir",
    headOfState: "Sheikh Mishal Al-Ahmad Al-Jaber Al-Sabah",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Sheikh Ahmad Al-Abdullah Al-Ahmad Al-Sabah",
    rulingParty: "House of Al-Sabah (no formal parties)",
    partySystem: "No formal parties; political blocs allowed",
    legislature: "National Assembly of Kuwait",
    legislatureStructure: "Unicameral",
    judiciary: "Constitutional Court of Kuwait",
    constitution: "Constitution of Kuwait",
    constitutionYear: 1962,
    economicModel: "Oil-based state economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/kuwait/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── MEXICO ───────────────────────────────────────────────
  MEX: {
    stateForm: "Federal presidential republic",
    governmentSystem: "Federal presidential constitutional republic",
    constitutionalIdentity: "Federal democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism", "Social democracy"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Directly elected President serves as head of state and government in a federal system.",
    headOfStateTitle: "President",
    headOfState: "Claudia Sheinbaum",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Claudia Sheinbaum",
    rulingParty: "Morena",
    partySystem: "Multi-party system",
    legislature: "Congress of the Union",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of Justice of the Nation",
    constitution: "Constitution of Mexico",
    constitutionYear: 1917,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/mexico/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ARGENTINA ────────────────────────────────────────────
  ARG: {
    stateForm: "Federal presidential republic",
    governmentSystem: "Federal presidential constitutional republic",
    constitutionalIdentity: "Federal republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Federalism", "Libertarianism (current government)"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral democracy",
    powerStructure: "Directly elected President serves as head of state and government.",
    headOfStateTitle: "President",
    headOfState: "Javier Milei",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Javier Milei",
    rulingParty: "La Libertad Avanza",
    partySystem: "Multi-party system",
    legislature: "National Congress of Argentina",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of Argentina",
    constitution: "Constitution of Argentina",
    constitutionYear: 1853,
    economicModel: "Mixed market economy (undergoing liberalization)",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/argentina/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── COLOMBIA ─────────────────────────────────────────────
  COL: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Social state governed by rule of law",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Electoral democracy",
    powerStructure: "Directly elected President serves as head of state and government.",
    headOfStateTitle: "President",
    headOfState: "Gustavo Petro",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Gustavo Petro",
    rulingParty: "Pacto Histórico coalition",
    partySystem: "Multi-party system",
    legislature: "Congress of Colombia",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court of Colombia",
    constitution: "Constitution of Colombia",
    constitutionYear: 1991,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/colombia/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── CHILE ────────────────────────────────────────────────
  CHL: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Presidential multi-party democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Directly elected President serves as head of state and government.",
    headOfStateTitle: "President",
    headOfState: "José Antonio Kast",
    headOfGovernmentTitle: "President",
    headOfGovernment: "José Antonio Kast",
    rulingParty: "Republican Party / Chile Vamos coalition",
    partySystem: "Multi-party system",
    legislature: "National Congress of Chile",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Tribunal of Chile",
    constitution: "Constitution of Chile",
    constitutionYear: 1980,
    economicModel: "Open market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/chile/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── NEW ZEALAND ──────────────────────────────────────────
  NZL: {
    stateForm: "Unitary parliamentary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional monarchy",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Constitutional monarchy"],
    politicalRegime: "Parliamentary democracy",
    regimeCategory: "Liberal democracy",
    powerStructure: "Prime Minister leads Cabinet; King Charles III is head of state.",
    headOfStateTitle: "Monarch",
    headOfState: "King Charles III",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Christopher Luxon",
    rulingParty: "New Zealand National Party / coalition",
    partySystem: "Multi-party system",
    legislature: "Parliament of New Zealand",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of New Zealand",
    constitution: "New Zealand Constitution Act 1986",
    constitutionYear: 1986,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/new-zealand/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── PAKISTAN ─────────────────────────────────────────────
  PAK: {
    stateForm: "Federal parliamentary republic",
    governmentSystem: "Federal parliamentary constitutional republic",
    constitutionalIdentity: "Islamic republic",
    officialIdeology: "Islam",
    ideologyFamily: ["Islamic republic", "Parliamentary democracy", "Federalism"],
    politicalRegime: "Parliamentary democracy with military influence",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Prime Minister leads government; President is largely ceremonial; military plays significant role.",
    headOfStateTitle: "President",
    headOfState: "Asif Ali Zardari",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Shehbaz Sharif",
    rulingParty: "Pakistan Muslim League-N (PML-N) / coalition",
    partySystem: "Multi-party system",
    legislature: "Parliament of Pakistan",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of Pakistan",
    constitution: "Constitution of Pakistan",
    constitutionYear: 1973,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/pakistan/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── BANGLADESH ───────────────────────────────────────────
  BGD: {
    stateForm: "Unitary parliamentary republic",
    governmentSystem: "Parliamentary constitutional republic",
    constitutionalIdentity: "People's republic",
    officialIdeology: "Nationalism; secularism; democracy; socialism",
    ideologyFamily: ["Liberal democracy", "Nationalism"],
    politicalRegime: "Parliamentary democracy (transitional)",
    regimeCategory: "Electoral autocracy",
    powerStructure: "Prime Minister leads government; President is largely ceremonial.",
    headOfStateTitle: "President",
    headOfState: "Mohammed Shahabuddin",
    headOfGovernmentTitle: "Chief Adviser",
    headOfGovernment: "Muhammad Yunus",
    rulingParty: "Interim government (post-Hasina)",
    partySystem: "Multi-party system (in transition)",
    legislature: "National Parliament (Jatiya Sangsad)",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Court of Bangladesh",
    constitution: "Constitution of Bangladesh",
    constitutionYear: 1972,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/bangladesh/", field: "governmentSystem" },
    ],
    confidenceLevel: "medium",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ALGERIA ──────────────────────────────────────────────
  DZA: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential republic",
    constitutionalIdentity: "People's Democratic Republic",
    officialIdeology: "Arab nationalism; Islam; socialism (historic)",
    ideologyFamily: ["Arab nationalism", "Statism"],
    politicalRegime: "Presidential republic with dominant ruling party",
    regimeCategory: "Closed autocracy",
    powerStructure: "President holds dominant executive power; Prime Minister leads government.",
    headOfStateTitle: "President",
    headOfState: "Abdelmadjid Tebboune",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Nadir Larbaoui",
    rulingParty: "National Liberation Front (FLN) / coalition",
    partySystem: "Dominant-party system",
    legislature: "Parliament of Algeria",
    legislatureStructure: "Bicameral",
    judiciary: "Supreme Court of Algeria",
    constitution: "Constitution of Algeria",
    constitutionYear: 1963,
    economicModel: "State-led economy with oil and gas exports",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/algeria/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── MOROCCO ──────────────────────────────────────────────
  MAR: {
    stateForm: "Unitary parliamentary constitutional monarchy",
    governmentSystem: "Parliamentary constitutional monarchy",
    constitutionalIdentity: "Constitutional, democratic, parliamentary and social monarchy",
    officialIdeology: "Islam; Arab-Amazigh identity; monarchism",
    ideologyFamily: ["Constitutional monarchy", "Arab nationalism"],
    politicalRegime: "Constitutional monarchy with parliamentary government",
    regimeCategory: "Electoral autocracy",
    powerStructure: "King holds significant executive power; Prime Minister leads government.",
    headOfStateTitle: "King",
    headOfState: "King Mohammed VI",
    headOfGovernmentTitle: "Head of Government",
    headOfGovernment: "Aziz Akhannouch",
    rulingParty: "National Rally of Independents (RNI) / coalition",
    partySystem: "Multi-party system",
    legislature: "Parliament of Morocco",
    legislatureStructure: "Bicameral",
    judiciary: "Constitutional Court of Morocco",
    constitution: "Constitution of Morocco",
    constitutionYear: 2011,
    economicModel: "Mixed market economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: true,
    isRepublic: false,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/morocco/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── ANGOLA ───────────────────────────────────────────────
  AGO: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential republic",
    constitutionalIdentity: "Democratic republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy (transitioning)", "Statism"],
    politicalRegime: "Presidential republic with dominant ruling party",
    regimeCategory: "Electoral autocracy",
    powerStructure: "President serves as both head of state and government.",
    headOfStateTitle: "President",
    headOfState: "João Lourenço",
    headOfGovernmentTitle: "President",
    headOfGovernment: "João Lourenço",
    rulingParty: "People's Movement for the Liberation of Angola (MPLA)",
    partySystem: "Dominant-party system",
    legislature: "National Assembly of Angola",
    legislatureStructure: "Unicameral",
    judiciary: "Constitutional Court of Angola",
    constitution: "Constitution of Angola",
    constitutionYear: 2010,
    economicModel: "Oil-dependent mixed economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/angola/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── UKRAINE ──────────────────────────────────────────────
  UKR: {
    stateForm: "Unitary semi-presidential republic",
    governmentSystem: "Semi-presidential constitutional republic",
    constitutionalIdentity: "Sovereign and democratic state",
    officialIdeology: "Ukrainian nationalism; European integration",
    ideologyFamily: ["Liberal democracy", "European integration"],
    politicalRegime: "Presidential republic with parliamentary elements",
    regimeCategory: "Electoral democracy",
    powerStructure: "President leads foreign/defense policy; Prime Minister leads domestic government.",
    headOfStateTitle: "President",
    headOfState: "Volodymyr Zelensky",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Denys Shmyhal",
    rulingParty: "Servant of the People",
    partySystem: "Multi-party system",
    legislature: "Verkhovna Rada",
    legislatureStructure: "Unicameral",
    judiciary: "Constitutional Court of Ukraine",
    constitution: "Constitution of Ukraine",
    constitutionYear: 1996,
    economicModel: "Mixed market economy (war economy)",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/ukraine/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── CUBA – lãnh đạo update ─────────────────────────────
  // (đã có structure từ trước, chỉ cần thêm lãnh đạo)
  // ── VENEZUELA ────────────────────────────────────────────
  VEN: {
    stateForm: "Federal presidential republic",
    governmentSystem: "Federal presidential republic",
    constitutionalIdentity: "Bolivarian republic",
    officialIdeology: "Bolivarian socialism; 21st century socialism",
    ideologyFamily: ["Socialism", "Bolivarianism", "Populism"],
    politicalRegime: "Presidential republic with authoritarian elements",
    regimeCategory: "Closed autocracy",
    powerStructure: "President holds extensive executive powers in a centralized political system.",
    headOfStateTitle: "President",
    headOfState: "Delcy Rodríguez",
    headOfGovernmentTitle: "President",
    headOfGovernment: "Delcy Rodríguez",
    rulingParty: "United Socialist Party of Venezuela (PSUV)",
    partySystem: "Dominant-party system",
    legislature: "National Assembly of Venezuela",
    legislatureStructure: "Unicameral",
    judiciary: "Supreme Tribunal of Justice",
    constitution: "Constitution of Venezuela",
    constitutionYear: 1999,
    economicModel: "State-led socialist economy",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: true,
    isUnitary: false,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/venezuela/", field: "governmentSystem" },
    ],
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
  // ── PERU ─────────────────────────────────────────────────
  PER: {
    stateForm: "Unitary presidential republic",
    governmentSystem: "Presidential constitutional republic",
    constitutionalIdentity: "Democratic and social republic",
    officialIdeology: "No single official ideology",
    ideologyFamily: ["Liberal democracy", "Republicanism"],
    politicalRegime: "Presidential democracy (political instability)",
    regimeCategory: "Electoral democracy",
    powerStructure: "President serves as head of state and government; strong Congress.",
    headOfStateTitle: "President",
    headOfState: "José María Balcázar",
    headOfGovernmentTitle: "President",
    headOfGovernment: "José María Balcázar",
    rulingParty: "Independent / interim government",
    partySystem: "Multi-party system (fragmented)",
    legislature: "Congress of Peru",
    legislatureStructure: "Unicameral",
    judiciary: "Constitutional Court of Peru",
    constitution: "Constitution of Peru",
    constitutionYear: 1993,
    economicModel: "Mixed market economy with mineral exports",
    hasCommunistRulingParty: false,
    hasMilitaryGovernment: false,
    isMonarchy: false,
    isRepublic: true,
    isFederal: false,
    isUnitary: true,
    sources: [
      { name: "CIA World Factbook", url: "https://www.cia.gov/the-world-factbook/countries/peru/", field: "governmentSystem" },
    ],
    confidenceLevel: "medium",
    dataUpdatedAt: "2026-06-05",
  },
  // ── CUBA lãnh đạo ─────────────────────────────────────────
  CUB: {
    headOfStateTitle: "President",
    headOfState: "Miguel Díaz-Canel",
    headOfGovernmentTitle: "Prime Minister",
    headOfGovernment: "Manuel Marrero Cruz",
    confidenceLevel: "high",
    dataUpdatedAt: "2026-06-05",
  },
};

// ─── Hàm patch ─────────────────────────────────────────────────────────────

function applyPatch(existing: Record<string, unknown>, patch: Record<string, unknown>): Record<string, unknown> {
  const result = { ...existing };
  for (const [key, value] of Object.entries(patch)) {
    // Chỉ patch nếu giá trị hiện tại là "Needs verification", null, undefined, hoặc patch muốn ghi đè
    const current = result[key];
    const isStale =
      current === "Needs verification" ||
      current === "Data unavailable" ||
      current === "Needs Verification" ||
      current === null ||
      current === undefined ||
      current === "" ||
      typeof current === "undefined";
    
    // Luôn cập nhật: headOfState, headOfGovernment, rulingParty, headOfStateTitle, headOfGovernmentTitle,
    // dataUpdatedAt, confidenceLevel (vì đây là time-sensitive fields)
    const alwaysUpdate = [
      "headOfState", "headOfGovernment", "rulingParty",
      "headOfStateTitle", "headOfGovernmentTitle",
      "dataUpdatedAt", "confidenceLevel",
    ];
    
    if (isStale || alwaysUpdate.includes(key)) {
      result[key] = value;
    }
  }
  return result;
}

// ─── Main ───────────────────────────────────────────────────────────────────

function main() {
  if (!fs.existsSync(DB_PATH)) {
    console.error(`❌ Database not found at: ${DB_PATH}`);
    process.exit(1);
  }

  const db = new DatabaseSync(DB_PATH, { timeout: 10000 });
  db.exec("PRAGMA journal_mode = WAL");

  // Lấy tất cả records
  const rows = db
    .prepare("SELECT iso3, profile_json FROM country_profiles")
    .all() as Array<{ iso3: string; profile_json: string }>;

  console.log(`📊 Loaded ${rows.length} country profiles from DB`);

  const update = db.prepare(
    "UPDATE country_profiles SET profile_json = ?, data_updated_at = ? WHERE iso3 = ?"
  );

  let patchedCount = 0;
  let skippedCount = 0;

  db.exec("BEGIN IMMEDIATE TRANSACTION");
  try {
    for (const row of rows) {
      const iso3 = row.iso3;
      const patch = PATCHES[iso3];

      if (!patch) {
        skippedCount++;
        continue;
      }

      const profile = JSON.parse(row.profile_json) as Record<string, unknown>;
      const patched = applyPatch(profile, patch);

      update.run(
        JSON.stringify(patched),
        String(patched.dataUpdatedAt ?? "2026-06-05"),
        iso3
      );

      patchedCount++;
      console.log(`  ✅ Patched: ${iso3} (${patched.countryName ?? iso3})`);
    }

    db.exec("COMMIT");
  } catch (error) {
    db.exec("ROLLBACK");
    throw error;
  } finally {
    db.close();
  }

  console.log(`\n✅ Done! Patched ${patchedCount} countries, skipped ${skippedCount} (no patch data).`);
  console.log(`📝 Countries without patches will be updated in future runs.`);
}

import { fileURLToPath } from "node:url";

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main();
}
